### ISSUE TITLE
not using public synonyms directly leads to - ORA-06550

### ISSUE THREAD

**Issue by tortureduck** [rsim/ruby-plsql#47] opened 2013-03-26 18:11 UTC
Dear Ray!

Following - guess pretty rare problem.
ruby_plsql executes procedures/functions always fully qualified SCHEMA.PACKAGE.PROCEDURE.
Even if it's a public synonym not the synonym is executed', e.g. I have synonym "exeme" 
that points to "scott.foo" "scott.foo" is executed and not "exeme".

That leads to the rare problem, that we have if a user, has the same name like an oracle-standard package.

-- this case does not work, because it's called directly and there is a package that has the same schema name 'SDO' in MDSYS schema

connect scott/tiger

DECLARE
  ret number;
BEGIN
  ret := SDO.abctest.testproc(NULL);
END;
/

connect scott/tiger

-- here it works, because here we created a public synonym for abctest (create public synonym abctest for sdo.abctest)
DECLARE
  ret number;
BEGIN
  ret := abctest.testproc(NULL);
END;
/

So plsql-ruby fails with PLS-00302: component 'ABCTEST' must be declared - ORA-06550.

I (ruby-noob) worked around with removing the schema name (@call_sql in procedure_call) if the object was retrieved through a synonym (by using a global variable -> shame on me!).
It is just the question if direct execution of the synonym would have any other advantage.
Sometimes there are side-effects as it's implemented now (rights-management?) other than this I described. if you don't execute the public synonym directly.

Manfred

P.S. 
plsql-ruby is really good work!

**Comment by jgebal** [comment] 2015-05-31 14:48
@tortureduck can you give a full example of steps to reproduce?

**Comment by jgebal** [comment] 2016-03-16 00:02
@tortureduck. The issue is hard to reproduce without an example.
Can you provide ruby/rspec code to reproduce the issue? Is it still an issue?

**Comment by tortureduck** [comment] 2016-03-21 18:27
Hi!

This should do the job, I have atm not a full ruby dev environment setup, therefore I am not able to provide a rspec, sorry for that!

Tx!

CREATE USER SDO IDENTIFIED BY SDO;
GRANT DBA TO SDO;
CONN SDO/SDO

CREATE OR REPLACE PACKAGE abctest IS
PROCEDURE testproc;
END;
/

CREATE OR REPLACE PACKAGE BODY abctest IS
PROCEDURE testproc IS
  BEGIN
    NULL;
  END;
END;
/

**Comment by tortureduck** [comment] 2016-03-21 18:30
To be honest thats pretty rare, but it probably points to some other kind of bug.

**Comment by jgebal** [comment] 2016-03-21 20:55
@tortureduck 
Please have a look at tests inside the framework, here:
https://github.com/rsim/ruby-plsql/blob/master/spec/plsql/package_spec.rb#L116
and here:
https://github.com/rsim/ruby-plsql/blob/master/spec/plsql/package_spec.rb#L154

Those are tests (passing) that validate that ruby-plsql is resolving package name from both private and public synonyms.

Could you provide similar test to the ones mentioned that show in what circumstances it's failing?

**Comment by jwassell** [comment] 2016-06-16 15:03
I'm having the same problem.  My oracle schema also has a package with the same name.  If I comment out  this line in procedure_call.rb it works:
@call_sql << "#{schema_name}." if schema_name 
@tortureduck can you give details on your workaround?

**Closed** 2018-01-20 12:05 UTC
Labels: wontfix
